/*
 * Waardering onroerende zaken
 *
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWOZObjectenApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>WozObjectHal</returns>
        WozObjectHal RaadpleegActueelWozobject(string identificatie, string fields = default(string));

        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>ApiResponse of WozObjectHal</returns>
        ApiResponse<WozObjectHal> RaadpleegActueelWozobjectWithHttpInfo(string identificatie, string fields = default(string));
        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <returns>WozObjectHalCollectie</returns>
        WozObjectHalCollectie ZoekActueleWozobjecten(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?));

        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <returns>ApiResponse of WozObjectHalCollectie</returns>
        ApiResponse<WozObjectHalCollectie> ZoekActueleWozobjectenWithHttpInfo(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWOZObjectenApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WozObjectHal</returns>
        System.Threading.Tasks.Task<WozObjectHal> RaadpleegActueelWozobjectAsync(string identificatie, string fields = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WozObjectHal)</returns>
        System.Threading.Tasks.Task<ApiResponse<WozObjectHal>> RaadpleegActueelWozobjectWithHttpInfoAsync(string identificatie, string fields = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WozObjectHalCollectie</returns>
        System.Threading.Tasks.Task<WozObjectHalCollectie> ZoekActueleWozobjectenAsync(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WozObjectHalCollectie)</returns>
        System.Threading.Tasks.Task<ApiResponse<WozObjectHalCollectie>> ZoekActueleWozobjectenWithHttpInfoAsync(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWOZObjectenApi : IWOZObjectenApiSync, IWOZObjectenApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WOZObjectenApi : IWOZObjectenApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WOZObjectenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WOZObjectenApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WOZObjectenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WOZObjectenApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WOZObjectenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WOZObjectenApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WOZObjectenApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public WOZObjectenApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>WozObjectHal</returns>
        public WozObjectHal RaadpleegActueelWozobject(string identificatie, string fields = default(string))
        {
            Org.OpenAPITools.Client.ApiResponse<WozObjectHal> localVarResponse = RaadpleegActueelWozobjectWithHttpInfo(identificatie, fields);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>ApiResponse of WozObjectHal</returns>
        public Org.OpenAPITools.Client.ApiResponse<WozObjectHal> RaadpleegActueelWozobjectWithHttpInfo(string identificatie, string fields = default(string))
        {
            // verify the required parameter 'identificatie' is set
            if (identificatie == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'identificatie' when calling WOZObjectenApi->RaadpleegActueelWozobject");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/hal+json",
                "application/problem+json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("identificatie", Org.OpenAPITools.Client.ClientUtils.ParameterToString(identificatie)); // path parameter
            if (fields != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "fields", fields));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<WozObjectHal>("/wozobjecten/{identificatie}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RaadpleegActueelWozobject", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WozObjectHal</returns>
        public async System.Threading.Tasks.Task<WozObjectHal> RaadpleegActueelWozobjectAsync(string identificatie, string fields = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<WozObjectHal> localVarResponse = await RaadpleegActueelWozobjectWithHttpInfoAsync(identificatie, fields, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WozObjectHal)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<WozObjectHal>> RaadpleegActueelWozobjectWithHttpInfoAsync(string identificatie, string fields = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'identificatie' is set
            if (identificatie == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'identificatie' when calling WOZObjectenApi->RaadpleegActueelWozobject");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/hal+json",
                "application/problem+json"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("identificatie", Org.OpenAPITools.Client.ClientUtils.ParameterToString(identificatie)); // path parameter
            if (fields != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "fields", fields));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<WozObjectHal>("/wozobjecten/{identificatie}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RaadpleegActueelWozobject", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <returns>WozObjectHalCollectie</returns>
        public WozObjectHalCollectie ZoekActueleWozobjecten(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?))
        {
            Org.OpenAPITools.Client.ApiResponse<WozObjectHalCollectie> localVarResponse = ZoekActueleWozobjectenWithHttpInfo(rsin, kvkNummer, adresseerbaarObjectIdentificatie, nummeraanduidingIdentificatie, postcode, huisnummer, huisnummertoevoeging, huisletter, fields, page, pageSize);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <returns>ApiResponse of WozObjectHalCollectie</returns>
        public Org.OpenAPITools.Client.ApiResponse<WozObjectHalCollectie> ZoekActueleWozobjectenWithHttpInfo(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?))
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/hal+json",
                "application/problem+json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (rsin != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "rsin", rsin));
            }
            if (kvkNummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "kvkNummer", kvkNummer));
            }
            if (adresseerbaarObjectIdentificatie != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "adresseerbaarObjectIdentificatie", adresseerbaarObjectIdentificatie));
            }
            if (nummeraanduidingIdentificatie != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "nummeraanduidingIdentificatie", nummeraanduidingIdentificatie));
            }
            if (postcode != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "postcode", postcode));
            }
            if (huisnummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "huisnummer", huisnummer));
            }
            if (huisnummertoevoeging != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "huisnummertoevoeging", huisnummertoevoeging));
            }
            if (huisletter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "huisletter", huisletter));
            }
            if (fields != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "fields", fields));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<WozObjectHalCollectie>("/wozobjecten", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ZoekActueleWozobjecten", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WozObjectHalCollectie</returns>
        public async System.Threading.Tasks.Task<WozObjectHalCollectie> ZoekActueleWozobjectenAsync(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<WozObjectHalCollectie> localVarResponse = await ZoekActueleWozobjectenWithHttpInfoAsync(rsin, kvkNummer, adresseerbaarObjectIdentificatie, nummeraanduidingIdentificatie, postcode, huisnummer, huisnummertoevoeging, huisletter, fields, page, pageSize, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\&quot; (optional)</param>
        /// <param name="huisnummertoevoeging">Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="huisletter">Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging  (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="page">Pagina nummer (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WozObjectHalCollectie)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<WozObjectHalCollectie>> ZoekActueleWozobjectenWithHttpInfoAsync(string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string huisnummertoevoeging = default(string), string huisletter = default(string), string fields = default(string), int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/hal+json",
                "application/problem+json"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (rsin != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "rsin", rsin));
            }
            if (kvkNummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "kvkNummer", kvkNummer));
            }
            if (adresseerbaarObjectIdentificatie != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "adresseerbaarObjectIdentificatie", adresseerbaarObjectIdentificatie));
            }
            if (nummeraanduidingIdentificatie != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "nummeraanduidingIdentificatie", nummeraanduidingIdentificatie));
            }
            if (postcode != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "postcode", postcode));
            }
            if (huisnummer != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "huisnummer", huisnummer));
            }
            if (huisnummertoevoeging != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "huisnummertoevoeging", huisnummertoevoeging));
            }
            if (huisletter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "huisletter", huisletter));
            }
            if (fields != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "fields", fields));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<WozObjectHalCollectie>("/wozobjecten", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ZoekActueleWozobjecten", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
