"""
    Waardering onroerende zaken

    Deze API levert actuele gegevens over WOZ-objecten   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError



class StatusBeschikkingEnum(ModelSimple):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('value',): {
            'BESCHIKKING_GENOMEN': "beschikking_genomen",
            'BESCHIKKING_VERNIETIGD': "beschikking_vernietigd",
            'BESCHIKKING_HERZIEN': "beschikking_herzien",
            'BEZWAAR_INGEDIEND': "bezwaar_ingediend",
            'BEZWAAR_GEHANDHAAFD': "bezwaar_gehandhaafd",
            'BEZWAAR_VERANDERD': "bezwaar_veranderd",
            'WAARDE_AMBTSHALVE_VERMINDERD': "waarde_ambtshalve_verminderd",
            'BEROEP_AANGETEKEND': "beroep_aangetekend",
            'BEROEP_GEHANDHAAFD': "beroep_gehandhaafd",
            'BEROEP_VERANDERD': "beroep_veranderd",
            'HOGER_BEROEP_AANGETEKEND': "hoger_beroep_aangetekend",
            'HOGER_BEROEP_GEHANDHAAFD': "hoger_beroep_gehandhaafd",
            'HOGER_BEROEP_VERANDERD': "hoger_beroep_veranderd",
            'CASSATIE_INGESTELD': "cassatie_ingesteld",
            'HOGE_RAAD_GEHANDHAAFD': "hoge_raad_gehandhaafd",
            'HOGE_RAAD_VERANDERD': "hoge_raad_veranderd",
            'HOGE_RAAD_GEDING_VERWEZEN': "hoge_raad_geding_verwezen",
            'VOORLOPIGE_AANSLAG': "voorlopige_aanslag",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'value': (str,),
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {}

    read_only_vars = set()

    _composed_schemas = None

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):
        """StatusBeschikkingEnum - a model defined in OpenAPI

        Note that value can be passed either in args or in kwargs, but not in both.

        Args:
            args[0] (str): De status van een beschikking waarmee de waarde is vastgesteld. * `beschikking_genomen` - 01: beschikking genomen * `beschikking_vernietigd` - 02: vernietigingbeschikking * `beschikking_herzien` - 03: herzieningsbeschikking * `bezwaar_ingediend` - 10: bezwaar ingediend * `bezwaar_gehandhaafd` - 11: bezwaar afgehandeld, beschikking gehandhaafd * `bezwaar_veranderd` - 12: bezwaar afgehandeld, vastgestelde waarde veranderd * `waarde_ambtshalve_verminderd` - 13: waarde ambtshalve verminderd * `beroep_aangetekend` - 20: beroepaangetekend * `beroep_gehandhaafd` - 21: uitspraak beroep, beschikking gehandhaafd * `beroep_veranderd` - 22: uitspraak beroep, vastgestelde waarde veranderd * `hoger_beroep_aangetekend` - 23: hogerberoep aangetekend * `hoger_beroep_gehandhaafd` - 24: uitspraak hoger beroep, beschikking gehandhaafd * `hoger_beroep_veranderd` - 25: uitspraak hoger beroep, vastgestelde waarde veranderd * `cassatie_ingesteld` - 30: cassatie ingesteld * `hoge_raad_gehandhaafd` - 31: arrest Hoge Raad, beschikking gehandhaafd * `hoge_raad_veranderd` - 32: arrest Hoge Raad, vastgestelde waarde veranderd * `hoge_raad_geding_verwezen` - 33: arrestHogeRaad,geding verwezen * `voorlopige_aanslag` - 99: waarde te gebruiken voor voorlopige aanslag ., must be one of ["beschikking_genomen", "beschikking_vernietigd", "beschikking_herzien", "bezwaar_ingediend", "bezwaar_gehandhaafd", "bezwaar_veranderd", "waarde_ambtshalve_verminderd", "beroep_aangetekend", "beroep_gehandhaafd", "beroep_veranderd", "hoger_beroep_aangetekend", "hoger_beroep_gehandhaafd", "hoger_beroep_veranderd", "cassatie_ingesteld", "hoge_raad_gehandhaafd", "hoge_raad_veranderd", "hoge_raad_geding_verwezen", "voorlopige_aanslag", ]  # noqa: E501

        Keyword Args:
            value (str): De status van een beschikking waarmee de waarde is vastgesteld. * `beschikking_genomen` - 01: beschikking genomen * `beschikking_vernietigd` - 02: vernietigingbeschikking * `beschikking_herzien` - 03: herzieningsbeschikking * `bezwaar_ingediend` - 10: bezwaar ingediend * `bezwaar_gehandhaafd` - 11: bezwaar afgehandeld, beschikking gehandhaafd * `bezwaar_veranderd` - 12: bezwaar afgehandeld, vastgestelde waarde veranderd * `waarde_ambtshalve_verminderd` - 13: waarde ambtshalve verminderd * `beroep_aangetekend` - 20: beroepaangetekend * `beroep_gehandhaafd` - 21: uitspraak beroep, beschikking gehandhaafd * `beroep_veranderd` - 22: uitspraak beroep, vastgestelde waarde veranderd * `hoger_beroep_aangetekend` - 23: hogerberoep aangetekend * `hoger_beroep_gehandhaafd` - 24: uitspraak hoger beroep, beschikking gehandhaafd * `hoger_beroep_veranderd` - 25: uitspraak hoger beroep, vastgestelde waarde veranderd * `cassatie_ingesteld` - 30: cassatie ingesteld * `hoge_raad_gehandhaafd` - 31: arrest Hoge Raad, beschikking gehandhaafd * `hoge_raad_veranderd` - 32: arrest Hoge Raad, vastgestelde waarde veranderd * `hoge_raad_geding_verwezen` - 33: arrestHogeRaad,geding verwezen * `voorlopige_aanslag` - 99: waarde te gebruiken voor voorlopige aanslag ., must be one of ["beschikking_genomen", "beschikking_vernietigd", "beschikking_herzien", "bezwaar_ingediend", "bezwaar_gehandhaafd", "bezwaar_veranderd", "waarde_ambtshalve_verminderd", "beroep_aangetekend", "beroep_gehandhaafd", "beroep_veranderd", "hoger_beroep_aangetekend", "hoger_beroep_gehandhaafd", "hoger_beroep_veranderd", "cassatie_ingesteld", "hoge_raad_gehandhaafd", "hoge_raad_veranderd", "hoge_raad_geding_verwezen", "voorlopige_aanslag", ]  # noqa: E501
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """
        # required up here when default value is not given
        _path_to_item = kwargs.pop('_path_to_item', ())

        if 'value' in kwargs:
            value = kwargs.pop('value')
        elif args:
            args = list(args)
            value = args.pop(0)
        else:
            raise ApiTypeError(
                "value is required, but not passed in args or kwargs and doesn't have default",
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)
        self.value = value
        if kwargs:
            raise ApiTypeError(
                "Invalid named arguments=%s passed to %s. Remove those invalid named arguments." % (
                    kwargs,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):
        """StatusBeschikkingEnum - a model defined in OpenAPI

        Note that value can be passed either in args or in kwargs, but not in both.

        Args:
            args[0] (str): De status van een beschikking waarmee de waarde is vastgesteld. * `beschikking_genomen` - 01: beschikking genomen * `beschikking_vernietigd` - 02: vernietigingbeschikking * `beschikking_herzien` - 03: herzieningsbeschikking * `bezwaar_ingediend` - 10: bezwaar ingediend * `bezwaar_gehandhaafd` - 11: bezwaar afgehandeld, beschikking gehandhaafd * `bezwaar_veranderd` - 12: bezwaar afgehandeld, vastgestelde waarde veranderd * `waarde_ambtshalve_verminderd` - 13: waarde ambtshalve verminderd * `beroep_aangetekend` - 20: beroepaangetekend * `beroep_gehandhaafd` - 21: uitspraak beroep, beschikking gehandhaafd * `beroep_veranderd` - 22: uitspraak beroep, vastgestelde waarde veranderd * `hoger_beroep_aangetekend` - 23: hogerberoep aangetekend * `hoger_beroep_gehandhaafd` - 24: uitspraak hoger beroep, beschikking gehandhaafd * `hoger_beroep_veranderd` - 25: uitspraak hoger beroep, vastgestelde waarde veranderd * `cassatie_ingesteld` - 30: cassatie ingesteld * `hoge_raad_gehandhaafd` - 31: arrest Hoge Raad, beschikking gehandhaafd * `hoge_raad_veranderd` - 32: arrest Hoge Raad, vastgestelde waarde veranderd * `hoge_raad_geding_verwezen` - 33: arrestHogeRaad,geding verwezen * `voorlopige_aanslag` - 99: waarde te gebruiken voor voorlopige aanslag ., must be one of ["beschikking_genomen", "beschikking_vernietigd", "beschikking_herzien", "bezwaar_ingediend", "bezwaar_gehandhaafd", "bezwaar_veranderd", "waarde_ambtshalve_verminderd", "beroep_aangetekend", "beroep_gehandhaafd", "beroep_veranderd", "hoger_beroep_aangetekend", "hoger_beroep_gehandhaafd", "hoger_beroep_veranderd", "cassatie_ingesteld", "hoge_raad_gehandhaafd", "hoge_raad_veranderd", "hoge_raad_geding_verwezen", "voorlopige_aanslag", ]  # noqa: E501

        Keyword Args:
            value (str): De status van een beschikking waarmee de waarde is vastgesteld. * `beschikking_genomen` - 01: beschikking genomen * `beschikking_vernietigd` - 02: vernietigingbeschikking * `beschikking_herzien` - 03: herzieningsbeschikking * `bezwaar_ingediend` - 10: bezwaar ingediend * `bezwaar_gehandhaafd` - 11: bezwaar afgehandeld, beschikking gehandhaafd * `bezwaar_veranderd` - 12: bezwaar afgehandeld, vastgestelde waarde veranderd * `waarde_ambtshalve_verminderd` - 13: waarde ambtshalve verminderd * `beroep_aangetekend` - 20: beroepaangetekend * `beroep_gehandhaafd` - 21: uitspraak beroep, beschikking gehandhaafd * `beroep_veranderd` - 22: uitspraak beroep, vastgestelde waarde veranderd * `hoger_beroep_aangetekend` - 23: hogerberoep aangetekend * `hoger_beroep_gehandhaafd` - 24: uitspraak hoger beroep, beschikking gehandhaafd * `hoger_beroep_veranderd` - 25: uitspraak hoger beroep, vastgestelde waarde veranderd * `cassatie_ingesteld` - 30: cassatie ingesteld * `hoge_raad_gehandhaafd` - 31: arrest Hoge Raad, beschikking gehandhaafd * `hoge_raad_veranderd` - 32: arrest Hoge Raad, vastgestelde waarde veranderd * `hoge_raad_geding_verwezen` - 33: arrestHogeRaad,geding verwezen * `voorlopige_aanslag` - 99: waarde te gebruiken voor voorlopige aanslag ., must be one of ["beschikking_genomen", "beschikking_vernietigd", "beschikking_herzien", "bezwaar_ingediend", "bezwaar_gehandhaafd", "bezwaar_veranderd", "waarde_ambtshalve_verminderd", "beroep_aangetekend", "beroep_gehandhaafd", "beroep_veranderd", "hoger_beroep_aangetekend", "hoger_beroep_gehandhaafd", "hoger_beroep_veranderd", "cassatie_ingesteld", "hoge_raad_gehandhaafd", "hoge_raad_veranderd", "hoge_raad_geding_verwezen", "voorlopige_aanslag", ]  # noqa: E501
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """
        # required up here when default value is not given
        _path_to_item = kwargs.pop('_path_to_item', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if 'value' in kwargs:
            value = kwargs.pop('value')
        elif args:
            args = list(args)
            value = args.pop(0)
        else:
            raise ApiTypeError(
                "value is required, but not passed in args or kwargs and doesn't have default",
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)
        self.value = value
        if kwargs:
            raise ApiTypeError(
                "Invalid named arguments=%s passed to %s. Remove those invalid named arguments." % (
                    kwargs,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        return self
