extends:
- spectral:oas
- ./allof-adds-property.yml
- ./allof-extends-object.yml
- ./allof-single-extension.yml
- ./enum-value-snake-case.yml
- ./query-parameter-names-camel-case.yml
- ./property-of-object-type.yml
- ./schema-names-pascal-case.yml
- ./too-much-information.yml
rules:
  oas3-unused-component: off
  oas3-valid-schema-example: off
  tag-description: off
  oas3-api-servers: off
  openapi-tags: off
  info-description: off
