/*
 * Waardering onroerende zaken
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.KadastraleAanduiding;

/**
 * KadastraalOnroerendeZaak
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-09T07:56:59.068811Z[Etc/UTC]")
public class KadastraalOnroerendeZaak {
  public static final String SERIALIZED_NAME_IDENTIFICATIE = "identificatie";
  @SerializedName(SERIALIZED_NAME_IDENTIFICATIE)
  private String identificatie;

  public static final String SERIALIZED_NAME_AANDUIDING = "aanduiding";
  @SerializedName(SERIALIZED_NAME_AANDUIDING)
  private KadastraleAanduiding aanduiding;

  public static final String SERIALIZED_NAME_AANDUIDING_MET_GEMEENTENAAM = "aanduidingMetGemeentenaam";
  @SerializedName(SERIALIZED_NAME_AANDUIDING_MET_GEMEENTENAAM)
  private String aanduidingMetGemeentenaam;


  public KadastraalOnroerendeZaak identificatie(String identificatie) {
    
    this.identificatie = identificatie;
    return this;
  }

   /**
   * Get identificatie
   * @return identificatie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIdentificatie() {
    return identificatie;
  }


  public void setIdentificatie(String identificatie) {
    this.identificatie = identificatie;
  }


  public KadastraalOnroerendeZaak aanduiding(KadastraleAanduiding aanduiding) {
    
    this.aanduiding = aanduiding;
    return this;
  }

   /**
   * Get aanduiding
   * @return aanduiding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KadastraleAanduiding getAanduiding() {
    return aanduiding;
  }


  public void setAanduiding(KadastraleAanduiding aanduiding) {
    this.aanduiding = aanduiding;
  }


  public KadastraalOnroerendeZaak aanduidingMetGemeentenaam(String aanduidingMetGemeentenaam) {
    
    this.aanduidingMetGemeentenaam = aanduidingMetGemeentenaam;
    return this;
  }

   /**
   * De volledige kadastraleAanduiding waarbij alle delen zijn samengevoegd en waarbij de gemeentenaam is gebruikt.
   * @return aanduidingMetGemeentenaam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "De volledige kadastraleAanduiding waarbij alle delen zijn samengevoegd en waarbij de gemeentenaam is gebruikt.")

  public String getAanduidingMetGemeentenaam() {
    return aanduidingMetGemeentenaam;
  }


  public void setAanduidingMetGemeentenaam(String aanduidingMetGemeentenaam) {
    this.aanduidingMetGemeentenaam = aanduidingMetGemeentenaam;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KadastraalOnroerendeZaak kadastraalOnroerendeZaak = (KadastraalOnroerendeZaak) o;
    return Objects.equals(this.identificatie, kadastraalOnroerendeZaak.identificatie) &&
        Objects.equals(this.aanduiding, kadastraalOnroerendeZaak.aanduiding) &&
        Objects.equals(this.aanduidingMetGemeentenaam, kadastraalOnroerendeZaak.aanduidingMetGemeentenaam);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificatie, aanduiding, aanduidingMetGemeentenaam);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KadastraalOnroerendeZaak {\n");
    sb.append("    identificatie: ").append(toIndentedString(identificatie)).append("\n");
    sb.append("    aanduiding: ").append(toIndentedString(aanduiding)).append("\n");
    sb.append("    aanduidingMetGemeentenaam: ").append(toIndentedString(aanduidingMetGemeentenaam)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

