/*
 * Waardering onroerende zaken
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * KadastraleAanduiding
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-09T07:56:59.068811Z[Etc/UTC]")
public class KadastraleAanduiding {
  public static final String SERIALIZED_NAME_GEMEENTECODE = "gemeentecode";
  @SerializedName(SERIALIZED_NAME_GEMEENTECODE)
  private String gemeentecode;

  public static final String SERIALIZED_NAME_SECTIE = "sectie";
  @SerializedName(SERIALIZED_NAME_SECTIE)
  private String sectie;

  public static final String SERIALIZED_NAME_PERCEELNUMMER = "perceelnummer";
  @SerializedName(SERIALIZED_NAME_PERCEELNUMMER)
  private Integer perceelnummer;

  public static final String SERIALIZED_NAME_DEELPERCEELNUMMER = "deelperceelnummer";
  @SerializedName(SERIALIZED_NAME_DEELPERCEELNUMMER)
  private String deelperceelnummer;

  public static final String SERIALIZED_NAME_APPARTEMENTSINDEX = "appartementsindex";
  @SerializedName(SERIALIZED_NAME_APPARTEMENTSINDEX)
  private Integer appartementsindex;


  public KadastraleAanduiding gemeentecode(String gemeentecode) {
    
    this.gemeentecode = gemeentecode;
    return this;
  }

   /**
   * Waar het kadaster de kadastrale gemeentenaam hanteert in de KadstraleAanduiding is in de WOZ de gemeentecode gebruikt.
   * @return gemeentecode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Waar het kadaster de kadastrale gemeentenaam hanteert in de KadstraleAanduiding is in de WOZ de gemeentecode gebruikt.")

  public String getGemeentecode() {
    return gemeentecode;
  }


  public void setGemeentecode(String gemeentecode) {
    this.gemeentecode = gemeentecode;
  }


  public KadastraleAanduiding sectie(String sectie) {
    
    this.sectie = sectie;
    return this;
  }

   /**
   * Sectie is een onderverdeling van de kadastrale gemeente, bedoeld om het werk van de meetdienst en de kadastrale kaarten overzichtelijk te houden. Per kadastrale gemeente zijn er max. 26x26 secties . Elke sectie heeft een of twee letters (bijv. \&quot;A\&quot;, &#39;B&#39;, ....&#39;AA&#39;, &#39;AB&#39;, ....&#39;ZZ&#39; . Alleen de sectieletter &#39;J&#39; wordt niet gebruikt om verwarring (handgeschreven) te voorkomen met &#39;I&#39;
   * @return sectie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sectie is een onderverdeling van de kadastrale gemeente, bedoeld om het werk van de meetdienst en de kadastrale kaarten overzichtelijk te houden. Per kadastrale gemeente zijn er max. 26x26 secties . Elke sectie heeft een of twee letters (bijv. \"A\", 'B', ....'AA', 'AB', ....'ZZ' . Alleen de sectieletter 'J' wordt niet gebruikt om verwarring (handgeschreven) te voorkomen met 'I'")

  public String getSectie() {
    return sectie;
  }


  public void setSectie(String sectie) {
    this.sectie = sectie;
  }


  public KadastraleAanduiding perceelnummer(Integer perceelnummer) {
    
    this.perceelnummer = perceelnummer;
    return this;
  }

   /**
   * Het perceelnummer dat een geheel perceel of een complex uniek identificeert binnen de sectie.
   * @return perceelnummer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Het perceelnummer dat een geheel perceel of een complex uniek identificeert binnen de sectie.")

  public Integer getPerceelnummer() {
    return perceelnummer;
  }


  public void setPerceelnummer(Integer perceelnummer) {
    this.perceelnummer = perceelnummer;
  }


  public KadastraleAanduiding deelperceelnummer(String deelperceelnummer) {
    
    this.deelperceelnummer = deelperceelnummer;
    return this;
  }

   /**
   * Get deelperceelnummer
   * @return deelperceelnummer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDeelperceelnummer() {
    return deelperceelnummer;
  }


  public void setDeelperceelnummer(String deelperceelnummer) {
    this.deelperceelnummer = deelperceelnummer;
  }


  public KadastraleAanduiding appartementsindex(Integer appartementsindex) {
    
    this.appartementsindex = appartementsindex;
    return this;
  }

   /**
   * Nummer dat het kadastraal object uniek identificeert als een appartementsrecht binnen het complex.
   * @return appartementsindex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Nummer dat het kadastraal object uniek identificeert als een appartementsrecht binnen het complex.")

  public Integer getAppartementsindex() {
    return appartementsindex;
  }


  public void setAppartementsindex(Integer appartementsindex) {
    this.appartementsindex = appartementsindex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KadastraleAanduiding kadastraleAanduiding = (KadastraleAanduiding) o;
    return Objects.equals(this.gemeentecode, kadastraleAanduiding.gemeentecode) &&
        Objects.equals(this.sectie, kadastraleAanduiding.sectie) &&
        Objects.equals(this.perceelnummer, kadastraleAanduiding.perceelnummer) &&
        Objects.equals(this.deelperceelnummer, kadastraleAanduiding.deelperceelnummer) &&
        Objects.equals(this.appartementsindex, kadastraleAanduiding.appartementsindex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gemeentecode, sectie, perceelnummer, deelperceelnummer, appartementsindex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KadastraleAanduiding {\n");
    sb.append("    gemeentecode: ").append(toIndentedString(gemeentecode)).append("\n");
    sb.append("    sectie: ").append(toIndentedString(sectie)).append("\n");
    sb.append("    perceelnummer: ").append(toIndentedString(perceelnummer)).append("\n");
    sb.append("    deelperceelnummer: ").append(toIndentedString(deelperceelnummer)).append("\n");
    sb.append("    appartementsindex: ").append(toIndentedString(appartementsindex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

