/*
 * Waardering onroerende zaken
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.StatusBeschikkingEnum;

/**
 * Waarde op de meest recente beschikking met betrekking tot de peildatum
 */
@ApiModel(description = "Waarde op de meest recente beschikking met betrekking tot de peildatum")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-09T07:56:59.068811Z[Etc/UTC]")
public class Waarde {
  public static final String SERIALIZED_NAME_VASTGESTELDE_WAARDE = "vastgesteldeWaarde";
  @SerializedName(SERIALIZED_NAME_VASTGESTELDE_WAARDE)
  private Integer vastgesteldeWaarde;

  public static final String SERIALIZED_NAME_WAARDEPEILDATUM = "waardepeildatum";
  @SerializedName(SERIALIZED_NAME_WAARDEPEILDATUM)
  private LocalDate waardepeildatum;

  public static final String SERIALIZED_NAME_INGANGSDATUM = "ingangsdatum";
  @SerializedName(SERIALIZED_NAME_INGANGSDATUM)
  private LocalDate ingangsdatum;

  public static final String SERIALIZED_NAME_BESCHIKKINGS_STATUSSEN = "beschikkingsStatussen";
  @SerializedName(SERIALIZED_NAME_BESCHIKKINGS_STATUSSEN)
  private List<StatusBeschikkingEnum> beschikkingsStatussen = null;


  public Waarde vastgesteldeWaarde(Integer vastgesteldeWaarde) {
    
    this.vastgesteldeWaarde = vastgesteldeWaarde;
    return this;
  }

   /**
   * Waarde van het WOZ-object op de peildatum in Euro
   * @return vastgesteldeWaarde
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "127000", value = "Waarde van het WOZ-object op de peildatum in Euro")

  public Integer getVastgesteldeWaarde() {
    return vastgesteldeWaarde;
  }


  public void setVastgesteldeWaarde(Integer vastgesteldeWaarde) {
    this.vastgesteldeWaarde = vastgesteldeWaarde;
  }


  public Waarde waardepeildatum(LocalDate waardepeildatum) {
    
    this.waardepeildatum = waardepeildatum;
    return this;
  }

   /**
   * Datum waarvoor de vastgestelde waarde geldt
   * @return waardepeildatum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Tue Jan 01 00:00:00 UTC 2019", value = "Datum waarvoor de vastgestelde waarde geldt")

  public LocalDate getWaardepeildatum() {
    return waardepeildatum;
  }


  public void setWaardepeildatum(LocalDate waardepeildatum) {
    this.waardepeildatum = waardepeildatum;
  }


  public Waarde ingangsdatum(LocalDate ingangsdatum) {
    
    this.ingangsdatum = ingangsdatum;
    return this;
  }

   /**
   * Datum vanaf wanneer de vastgestelde waarde geldt
   * @return ingangsdatum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Wed Jan 01 00:00:00 UTC 2020", value = "Datum vanaf wanneer de vastgestelde waarde geldt")

  public LocalDate getIngangsdatum() {
    return ingangsdatum;
  }


  public void setIngangsdatum(LocalDate ingangsdatum) {
    this.ingangsdatum = ingangsdatum;
  }


  public Waarde beschikkingsStatussen(List<StatusBeschikkingEnum> beschikkingsStatussen) {
    
    this.beschikkingsStatussen = beschikkingsStatussen;
    return this;
  }

  public Waarde addBeschikkingsStatussenItem(StatusBeschikkingEnum beschikkingsStatussenItem) {
    if (this.beschikkingsStatussen == null) {
      this.beschikkingsStatussen = new ArrayList<>();
    }
    this.beschikkingsStatussen.add(beschikkingsStatussenItem);
    return this;
  }

   /**
   * Een of meer actuele statussen van de vastgestelde waarde
   * @return beschikkingsStatussen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Een of meer actuele statussen van de vastgestelde waarde")

  public List<StatusBeschikkingEnum> getBeschikkingsStatussen() {
    return beschikkingsStatussen;
  }


  public void setBeschikkingsStatussen(List<StatusBeschikkingEnum> beschikkingsStatussen) {
    this.beschikkingsStatussen = beschikkingsStatussen;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Waarde waarde = (Waarde) o;
    return Objects.equals(this.vastgesteldeWaarde, waarde.vastgesteldeWaarde) &&
        Objects.equals(this.waardepeildatum, waarde.waardepeildatum) &&
        Objects.equals(this.ingangsdatum, waarde.ingangsdatum) &&
        Objects.equals(this.beschikkingsStatussen, waarde.beschikkingsStatussen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vastgesteldeWaarde, waardepeildatum, ingangsdatum, beschikkingsStatussen);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Waarde {\n");
    sb.append("    vastgesteldeWaarde: ").append(toIndentedString(vastgesteldeWaarde)).append("\n");
    sb.append("    waardepeildatum: ").append(toIndentedString(waardepeildatum)).append("\n");
    sb.append("    ingangsdatum: ").append(toIndentedString(ingangsdatum)).append("\n");
    sb.append("    beschikkingsStatussen: ").append(toIndentedString(beschikkingsStatussen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

