/*
 * Waardering onroerende zaken
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

/**
 * Waarde op de meest recente beschikking met betrekking tot de peildatum
 */
@ApiModel(description = "Waarde op de meest recente beschikking met betrekking tot de peildatum")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-12T10:15:17.976Z[Etc/UTC]")
public class Waarde {
  public static final String SERIALIZED_NAME_VASTGESTELDE_WAARDE = "vastgesteldeWaarde";
  @SerializedName(SERIALIZED_NAME_VASTGESTELDE_WAARDE)
  private Integer vastgesteldeWaarde;

  public static final String SERIALIZED_NAME_INDICATIE_BEZWAAR_BEROEP = "indicatieBezwaarBeroep";
  @SerializedName(SERIALIZED_NAME_INDICATIE_BEZWAAR_BEROEP)
  private Boolean indicatieBezwaarBeroep;

  public static final String SERIALIZED_NAME_WAARDEPEILDATUM = "waardepeildatum";
  @SerializedName(SERIALIZED_NAME_WAARDEPEILDATUM)
  private LocalDate waardepeildatum;


  public Waarde vastgesteldeWaarde(Integer vastgesteldeWaarde) {
    
    this.vastgesteldeWaarde = vastgesteldeWaarde;
    return this;
  }

   /**
   * Waarde van het WOZ-object op de peildatum in Euro
   * @return vastgesteldeWaarde
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Waarde van het WOZ-object op de peildatum in Euro")

  public Integer getVastgesteldeWaarde() {
    return vastgesteldeWaarde;
  }


  public void setVastgesteldeWaarde(Integer vastgesteldeWaarde) {
    this.vastgesteldeWaarde = vastgesteldeWaarde;
  }


  public Waarde indicatieBezwaarBeroep(Boolean indicatieBezwaarBeroep) {
    
    this.indicatieBezwaarBeroep = indicatieBezwaarBeroep;
    return this;
  }

   /**
   * Bij waarde true is er een lopende zaak voor bezwaar, beroep, hoger beroep of cassatie
   * @return indicatieBezwaarBeroep
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Bij waarde true is er een lopende zaak voor bezwaar, beroep, hoger beroep of cassatie")

  public Boolean getIndicatieBezwaarBeroep() {
    return indicatieBezwaarBeroep;
  }


  public void setIndicatieBezwaarBeroep(Boolean indicatieBezwaarBeroep) {
    this.indicatieBezwaarBeroep = indicatieBezwaarBeroep;
  }


  public Waarde waardepeildatum(LocalDate waardepeildatum) {
    
    this.waardepeildatum = waardepeildatum;
    return this;
  }

   /**
   * Datum waarvoor de vastgestelde waarde geldt
   * @return waardepeildatum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Tue Jan 01 00:00:00 UTC 2019", value = "Datum waarvoor de vastgestelde waarde geldt")

  public LocalDate getWaardepeildatum() {
    return waardepeildatum;
  }


  public void setWaardepeildatum(LocalDate waardepeildatum) {
    this.waardepeildatum = waardepeildatum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Waarde waarde = (Waarde) o;
    return Objects.equals(this.vastgesteldeWaarde, waarde.vastgesteldeWaarde) &&
        Objects.equals(this.indicatieBezwaarBeroep, waarde.indicatieBezwaarBeroep) &&
        Objects.equals(this.waardepeildatum, waarde.waardepeildatum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vastgesteldeWaarde, indicatieBezwaarBeroep, waardepeildatum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Waarde {\n");
    sb.append("    vastgesteldeWaarde: ").append(toIndentedString(vastgesteldeWaarde)).append("\n");
    sb.append("    indicatieBezwaarBeroep: ").append(toIndentedString(indicatieBezwaarBeroep)).append("\n");
    sb.append("    waardepeildatum: ").append(toIndentedString(waardepeildatum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

