/*
 * Waardering onroerende zaken
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.HalLink;

/**
 * WozObjectBasisLinks
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-09T07:56:59.068811Z[Etc/UTC]")
public class WozObjectBasisLinks {
  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  private HalLink self;

  public static final String SERIALIZED_NAME_ADRES = "adres";
  @SerializedName(SERIALIZED_NAME_ADRES)
  private HalLink adres;

  public static final String SERIALIZED_NAME_ADRESSEERBARE_OBJECTEN = "adresseerbareObjecten";
  @SerializedName(SERIALIZED_NAME_ADRESSEERBARE_OBJECTEN)
  private List<HalLink> adresseerbareObjecten = null;

  public static final String SERIALIZED_NAME_BELANGHEBBENDE_EIGENAAR = "belanghebbendeEigenaar";
  @SerializedName(SERIALIZED_NAME_BELANGHEBBENDE_EIGENAAR)
  private HalLink belanghebbendeEigenaar;

  public static final String SERIALIZED_NAME_BELANGHEBBENDE_GEBRUIKER = "belanghebbendeGebruiker";
  @SerializedName(SERIALIZED_NAME_BELANGHEBBENDE_GEBRUIKER)
  private HalLink belanghebbendeGebruiker;

  public static final String SERIALIZED_NAME_PANDEN = "panden";
  @SerializedName(SERIALIZED_NAME_PANDEN)
  private List<HalLink> panden = null;

  public static final String SERIALIZED_NAME_KADASTRAAL_ONROERENDE_ZAKEN = "kadastraalOnroerendeZaken";
  @SerializedName(SERIALIZED_NAME_KADASTRAAL_ONROERENDE_ZAKEN)
  private List<HalLink> kadastraalOnroerendeZaken = null;


  public WozObjectBasisLinks self(HalLink self) {
    
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getSelf() {
    return self;
  }


  public void setSelf(HalLink self) {
    this.self = self;
  }


  public WozObjectBasisLinks adres(HalLink adres) {
    
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getAdres() {
    return adres;
  }


  public void setAdres(HalLink adres) {
    this.adres = adres;
  }


  public WozObjectBasisLinks adresseerbareObjecten(List<HalLink> adresseerbareObjecten) {
    
    this.adresseerbareObjecten = adresseerbareObjecten;
    return this;
  }

  public WozObjectBasisLinks addAdresseerbareObjectenItem(HalLink adresseerbareObjectenItem) {
    if (this.adresseerbareObjecten == null) {
      this.adresseerbareObjecten = new ArrayList<>();
    }
    this.adresseerbareObjecten.add(adresseerbareObjectenItem);
    return this;
  }

   /**
   * Get adresseerbareObjecten
   * @return adresseerbareObjecten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<HalLink> getAdresseerbareObjecten() {
    return adresseerbareObjecten;
  }


  public void setAdresseerbareObjecten(List<HalLink> adresseerbareObjecten) {
    this.adresseerbareObjecten = adresseerbareObjecten;
  }


  public WozObjectBasisLinks belanghebbendeEigenaar(HalLink belanghebbendeEigenaar) {
    
    this.belanghebbendeEigenaar = belanghebbendeEigenaar;
    return this;
  }

   /**
   * Get belanghebbendeEigenaar
   * @return belanghebbendeEigenaar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getBelanghebbendeEigenaar() {
    return belanghebbendeEigenaar;
  }


  public void setBelanghebbendeEigenaar(HalLink belanghebbendeEigenaar) {
    this.belanghebbendeEigenaar = belanghebbendeEigenaar;
  }


  public WozObjectBasisLinks belanghebbendeGebruiker(HalLink belanghebbendeGebruiker) {
    
    this.belanghebbendeGebruiker = belanghebbendeGebruiker;
    return this;
  }

   /**
   * Get belanghebbendeGebruiker
   * @return belanghebbendeGebruiker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getBelanghebbendeGebruiker() {
    return belanghebbendeGebruiker;
  }


  public void setBelanghebbendeGebruiker(HalLink belanghebbendeGebruiker) {
    this.belanghebbendeGebruiker = belanghebbendeGebruiker;
  }


  public WozObjectBasisLinks panden(List<HalLink> panden) {
    
    this.panden = panden;
    return this;
  }

  public WozObjectBasisLinks addPandenItem(HalLink pandenItem) {
    if (this.panden == null) {
      this.panden = new ArrayList<>();
    }
    this.panden.add(pandenItem);
    return this;
  }

   /**
   * Get panden
   * @return panden
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<HalLink> getPanden() {
    return panden;
  }


  public void setPanden(List<HalLink> panden) {
    this.panden = panden;
  }


  public WozObjectBasisLinks kadastraalOnroerendeZaken(List<HalLink> kadastraalOnroerendeZaken) {
    
    this.kadastraalOnroerendeZaken = kadastraalOnroerendeZaken;
    return this;
  }

  public WozObjectBasisLinks addKadastraalOnroerendeZakenItem(HalLink kadastraalOnroerendeZakenItem) {
    if (this.kadastraalOnroerendeZaken == null) {
      this.kadastraalOnroerendeZaken = new ArrayList<>();
    }
    this.kadastraalOnroerendeZaken.add(kadastraalOnroerendeZakenItem);
    return this;
  }

   /**
   * Get kadastraalOnroerendeZaken
   * @return kadastraalOnroerendeZaken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<HalLink> getKadastraalOnroerendeZaken() {
    return kadastraalOnroerendeZaken;
  }


  public void setKadastraalOnroerendeZaken(List<HalLink> kadastraalOnroerendeZaken) {
    this.kadastraalOnroerendeZaken = kadastraalOnroerendeZaken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WozObjectBasisLinks wozObjectBasisLinks = (WozObjectBasisLinks) o;
    return Objects.equals(this.self, wozObjectBasisLinks.self) &&
        Objects.equals(this.adres, wozObjectBasisLinks.adres) &&
        Objects.equals(this.adresseerbareObjecten, wozObjectBasisLinks.adresseerbareObjecten) &&
        Objects.equals(this.belanghebbendeEigenaar, wozObjectBasisLinks.belanghebbendeEigenaar) &&
        Objects.equals(this.belanghebbendeGebruiker, wozObjectBasisLinks.belanghebbendeGebruiker) &&
        Objects.equals(this.panden, wozObjectBasisLinks.panden) &&
        Objects.equals(this.kadastraalOnroerendeZaken, wozObjectBasisLinks.kadastraalOnroerendeZaken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, adres, adresseerbareObjecten, belanghebbendeEigenaar, belanghebbendeGebruiker, panden, kadastraalOnroerendeZaken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WozObjectBasisLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("    adresseerbareObjecten: ").append(toIndentedString(adresseerbareObjecten)).append("\n");
    sb.append("    belanghebbendeEigenaar: ").append(toIndentedString(belanghebbendeEigenaar)).append("\n");
    sb.append("    belanghebbendeGebruiker: ").append(toIndentedString(belanghebbendeGebruiker)).append("\n");
    sb.append("    panden: ").append(toIndentedString(panden)).append("\n");
    sb.append("    kadastraalOnroerendeZaken: ").append(toIndentedString(kadastraalOnroerendeZaken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

