/*
 * Waardering onroerende zaken
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.HalLink;

/**
 * WozObjectBasisLinks
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-06T08:39:14.200Z[Etc/UTC]")
public class WozObjectBasisLinks {
  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  private HalLink self;

  public static final String SERIALIZED_NAME_ADRES = "adres";
  @SerializedName(SERIALIZED_NAME_ADRES)
  private HalLink adres;

  public static final String SERIALIZED_NAME_ADRESSEERBAAR_OBJECTEN = "adresseerbaarObjecten";
  @SerializedName(SERIALIZED_NAME_ADRESSEERBAAR_OBJECTEN)
  private List<HalLink> adresseerbaarObjecten = null;

  public static final String SERIALIZED_NAME_BELANGHEBBEND_EIGENAAR = "belanghebbendEigenaar";
  @SerializedName(SERIALIZED_NAME_BELANGHEBBEND_EIGENAAR)
  private HalLink belanghebbendEigenaar;

  public static final String SERIALIZED_NAME_BELANGHEBBEND_GEBRUIKER = "belanghebbendGebruiker";
  @SerializedName(SERIALIZED_NAME_BELANGHEBBEND_GEBRUIKER)
  private HalLink belanghebbendGebruiker;

  public static final String SERIALIZED_NAME_PANDEN = "panden";
  @SerializedName(SERIALIZED_NAME_PANDEN)
  private List<HalLink> panden = null;


  public WozObjectBasisLinks self(HalLink self) {
    
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getSelf() {
    return self;
  }


  public void setSelf(HalLink self) {
    this.self = self;
  }


  public WozObjectBasisLinks adres(HalLink adres) {
    
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getAdres() {
    return adres;
  }


  public void setAdres(HalLink adres) {
    this.adres = adres;
  }


  public WozObjectBasisLinks adresseerbaarObjecten(List<HalLink> adresseerbaarObjecten) {
    
    this.adresseerbaarObjecten = adresseerbaarObjecten;
    return this;
  }

  public WozObjectBasisLinks addAdresseerbaarObjectenItem(HalLink adresseerbaarObjectenItem) {
    if (this.adresseerbaarObjecten == null) {
      this.adresseerbaarObjecten = new ArrayList<>();
    }
    this.adresseerbaarObjecten.add(adresseerbaarObjectenItem);
    return this;
  }

   /**
   * Get adresseerbaarObjecten
   * @return adresseerbaarObjecten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<HalLink> getAdresseerbaarObjecten() {
    return adresseerbaarObjecten;
  }


  public void setAdresseerbaarObjecten(List<HalLink> adresseerbaarObjecten) {
    this.adresseerbaarObjecten = adresseerbaarObjecten;
  }


  public WozObjectBasisLinks belanghebbendEigenaar(HalLink belanghebbendEigenaar) {
    
    this.belanghebbendEigenaar = belanghebbendEigenaar;
    return this;
  }

   /**
   * Get belanghebbendEigenaar
   * @return belanghebbendEigenaar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getBelanghebbendEigenaar() {
    return belanghebbendEigenaar;
  }


  public void setBelanghebbendEigenaar(HalLink belanghebbendEigenaar) {
    this.belanghebbendEigenaar = belanghebbendEigenaar;
  }


  public WozObjectBasisLinks belanghebbendGebruiker(HalLink belanghebbendGebruiker) {
    
    this.belanghebbendGebruiker = belanghebbendGebruiker;
    return this;
  }

   /**
   * Get belanghebbendGebruiker
   * @return belanghebbendGebruiker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getBelanghebbendGebruiker() {
    return belanghebbendGebruiker;
  }


  public void setBelanghebbendGebruiker(HalLink belanghebbendGebruiker) {
    this.belanghebbendGebruiker = belanghebbendGebruiker;
  }


  public WozObjectBasisLinks panden(List<HalLink> panden) {
    
    this.panden = panden;
    return this;
  }

  public WozObjectBasisLinks addPandenItem(HalLink pandenItem) {
    if (this.panden == null) {
      this.panden = new ArrayList<>();
    }
    this.panden.add(pandenItem);
    return this;
  }

   /**
   * Get panden
   * @return panden
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<HalLink> getPanden() {
    return panden;
  }


  public void setPanden(List<HalLink> panden) {
    this.panden = panden;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WozObjectBasisLinks wozObjectBasisLinks = (WozObjectBasisLinks) o;
    return Objects.equals(this.self, wozObjectBasisLinks.self) &&
        Objects.equals(this.adres, wozObjectBasisLinks.adres) &&
        Objects.equals(this.adresseerbaarObjecten, wozObjectBasisLinks.adresseerbaarObjecten) &&
        Objects.equals(this.belanghebbendEigenaar, wozObjectBasisLinks.belanghebbendEigenaar) &&
        Objects.equals(this.belanghebbendGebruiker, wozObjectBasisLinks.belanghebbendGebruiker) &&
        Objects.equals(this.panden, wozObjectBasisLinks.panden);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, adres, adresseerbaarObjecten, belanghebbendEigenaar, belanghebbendGebruiker, panden);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WozObjectBasisLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("    adresseerbaarObjecten: ").append(toIndentedString(adresseerbaarObjecten)).append("\n");
    sb.append("    belanghebbendEigenaar: ").append(toIndentedString(belanghebbendEigenaar)).append("\n");
    sb.append("    belanghebbendGebruiker: ").append(toIndentedString(belanghebbendGebruiker)).append("\n");
    sb.append("    panden: ").append(toIndentedString(panden)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

