"""
    Waardering onroerende zaken

    Deze API levert actuele gegevens over WOZ-objecten   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.model.foutbericht import Foutbericht
from openapi_client.model.woz_object_hal import WozObjectHal
from openapi_client.model.woz_object_hal_collectie import WozObjectHalCollectie


class WOZObjectenApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.raadpleeg_actueel_wozobject_endpoint = _Endpoint(
            settings={
                'response_type': (WozObjectHal,),
                'auth': [],
                'endpoint_path': '/wozobjecten/{identificatie}',
                'operation_id': 'raadpleeg_actueel_wozobject',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'identificatie',
                    'fields',
                ],
                'required': [
                    'identificatie',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'identificatie',
                ]
            },
            root_map={
                'validations': {
                    ('identificatie',): {

                        'regex': {
                            'pattern': r'^[0-9]{12}$',  # noqa: E501
                        },
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'identificatie':
                        (str,),
                    'fields':
                        (str,),
                },
                'attribute_map': {
                    'identificatie': 'identificatie',
                    'fields': 'fields',
                },
                'location_map': {
                    'identificatie': 'path',
                    'fields': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/hal+json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.zoek_actuele_wozobjecten_endpoint = _Endpoint(
            settings={
                'response_type': (WozObjectHalCollectie,),
                'auth': [],
                'endpoint_path': '/wozobjecten',
                'operation_id': 'zoek_actuele_wozobjecten',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'rsin',
                    'kvk_nummer',
                    'adresseerbaar_object_identificatie',
                    'nummeraanduiding_identificatie',
                    'postcode',
                    'huisnummer',
                    'huisnummertoevoeging',
                    'huisletter',
                    'fields',
                    'page',
                    'page_size',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'rsin',
                    'kvk_nummer',
                    'adresseerbaar_object_identificatie',
                    'nummeraanduiding_identificatie',
                    'postcode',
                    'huisnummer',
                    'huisnummertoevoeging',
                    'huisletter',
                    'page',
                    'page_size',
                ]
            },
            root_map={
                'validations': {
                    ('rsin',): {

                        'regex': {
                            'pattern': r'^[0-9]{9}$',  # noqa: E501
                        },
                    },
                    ('kvk_nummer',): {

                        'regex': {
                            'pattern': r'^[0-9]{8}$',  # noqa: E501
                        },
                    },
                    ('adresseerbaar_object_identificatie',): {

                        'regex': {
                            'pattern': r'^[0-9]{16}$',  # noqa: E501
                        },
                    },
                    ('nummeraanduiding_identificatie',): {

                        'regex': {
                            'pattern': r'^[0-9]{16}$',  # noqa: E501
                        },
                    },
                    ('postcode',): {

                        'regex': {
                            'pattern': r'^[1-9][0-9]{3}[A-Z]{2}$',  # noqa: E501
                        },
                    },
                    ('huisnummer',): {

                        'inclusive_maximum': 99999,
                        'inclusive_minimum': 1,
                    },
                    ('huisnummertoevoeging',): {

                        'regex': {
                            'pattern': r'^[0-9a-zA-Z]{1,4}$',  # noqa: E501
                        },
                    },
                    ('huisletter',): {

                        'regex': {
                            'pattern': r'^[a-zA-Z]$',  # noqa: E501
                        },
                    },
                    ('page',): {

                        'inclusive_minimum': 1,
                    },
                    ('page_size',): {

                        'inclusive_maximum': 100,
                        'inclusive_minimum': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'rsin':
                        (str,),
                    'kvk_nummer':
                        (str,),
                    'adresseerbaar_object_identificatie':
                        (str,),
                    'nummeraanduiding_identificatie':
                        (str,),
                    'postcode':
                        (str,),
                    'huisnummer':
                        (int,),
                    'huisnummertoevoeging':
                        (str,),
                    'huisletter':
                        (str,),
                    'fields':
                        (str,),
                    'page':
                        (int,),
                    'page_size':
                        (int,),
                },
                'attribute_map': {
                    'rsin': 'rsin',
                    'kvk_nummer': 'kvkNummer',
                    'adresseerbaar_object_identificatie': 'adresseerbaarObjectIdentificatie',
                    'nummeraanduiding_identificatie': 'nummeraanduidingIdentificatie',
                    'postcode': 'postcode',
                    'huisnummer': 'huisnummer',
                    'huisnummertoevoeging': 'huisnummertoevoeging',
                    'huisletter': 'huisletter',
                    'fields': 'fields',
                    'page': 'page',
                    'page_size': 'pageSize',
                },
                'location_map': {
                    'rsin': 'query',
                    'kvk_nummer': 'query',
                    'adresseerbaar_object_identificatie': 'query',
                    'nummeraanduiding_identificatie': 'query',
                    'postcode': 'query',
                    'huisnummer': 'query',
                    'huisnummertoevoeging': 'query',
                    'huisletter': 'query',
                    'fields': 'query',
                    'page': 'query',
                    'page_size': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/hal+json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

    def raadpleeg_actueel_wozobject(
        self,
        identificatie,
        **kwargs
    ):
        """Raadpleeg een WOZ-object  # noqa: E501

        Raadpleeg de actuele eigenschappen van een WOZ-object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.raadpleeg_actueel_wozobject(identificatie, async_req=True)
        >>> result = thread.get()

        Args:
            identificatie (str): Unieke identificatie van een WOZ-object

        Keyword Args:
            fields (str): Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma's gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature). [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            WozObjectHal
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['identificatie'] = \
            identificatie
        return self.raadpleeg_actueel_wozobject_endpoint.call_with_http_info(**kwargs)

    def zoek_actuele_wozobjecten(
        self,
        **kwargs
    ):
        """Zoek WOZ-objecten  # noqa: E501

        Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.zoek_actuele_wozobjecten(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            rsin (str): Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon. [optional]
            kvk_nummer (str): Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen. [optional]
            adresseerbaar_object_identificatie (str): Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is. [optional]
            nummeraanduiding_identificatie (str): Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid. [optional]
            postcode (str): Zoek WOZ-objecten met postcode, in combinatie met huisnummer en eventueel met huisletter en/of huisnummertoevoeging. [optional]
            huisnummer (int): Zoek WOZ-objecten met huisnummer, in combinatie met postcode en eventueel met huisletter en/of huisnummertoevoeging\". [optional]
            huisnummertoevoeging (str): Zoek met een huisnummertoevoeging, in combinatie met postcode en huisnummer en eventueel huisletter. Dit is een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging . [optional]
            huisletter (str): Zoek met een huisletter, in combinatie met postcode en huisnummer en eventueel huisnummertoevoeging. Dit is een toevoeging aan een huisnummer en huisnummertoevoeging. Bijvoorbeeld bij Belgiëlaan 1 A3 is 1 het huisnummer, A de huisletter en 3 de huisnummertoevoeging . [optional]
            fields (str): Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma's gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature). [optional]
            page (int): Pagina nummer. [optional] if omitted the server will use the default value of 1
            page_size (int): [optional] if omitted the server will use the default value of 20
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            WozObjectHalCollectie
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_host_index'] = kwargs.get('_host_index')
        return self.zoek_actuele_wozobjecten_endpoint.call_with_http_info(**kwargs)

