"""
    Waardering onroerende zaken

    Deze API levert actuele gegevens over WOZ-objecten   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.model.foutbericht import Foutbericht
from openapi_client.model.woz_object_hal import WozObjectHal
from openapi_client.model.woz_object_hal_collectie import WozObjectHalCollectie


class WOZObjectenApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __raadpleeg_actueel_wozobject(
            self,
            identificatie,
            **kwargs
        ):
            """Raadpleeg een WOZ-object  # noqa: E501

            Raadpleeg de actuele eigenschappen van een WOZ-object  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.raadpleeg_actueel_wozobject(identificatie, async_req=True)
            >>> result = thread.get()

            Args:
                identificatie (str): Unieke identificatie van een WOZ-object

            Keyword Args:
                fields (str): Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma's gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature). [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WozObjectHal
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['identificatie'] = \
                identificatie
            return self.call_with_http_info(**kwargs)

        self.raadpleeg_actueel_wozobject = Endpoint(
            settings={
                'response_type': (WozObjectHal,),
                'auth': [],
                'endpoint_path': '/wozobjecten/{identificatie}',
                'operation_id': 'raadpleeg_actueel_wozobject',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'identificatie',
                    'fields',
                ],
                'required': [
                    'identificatie',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'identificatie':
                        (str,),
                    'fields':
                        (str,),
                },
                'attribute_map': {
                    'identificatie': 'identificatie',
                    'fields': 'fields',
                },
                'location_map': {
                    'identificatie': 'path',
                    'fields': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/hal+json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__raadpleeg_actueel_wozobject
        )

        def __zoek_actuele_wozobjecten(
            self,
            **kwargs
        ):
            """Zoek WOZ-objecten  # noqa: E501

            Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.zoek_actuele_wozobjecten(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                rsin (str): Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon. [optional]
                kvk_nummer (str): Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen. [optional]
                adresseerbaar_object_identificatie (str): Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent. [optional]
                nummeraanduiding_identificatie (str): Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid. [optional]
                postcode (str): Zoek WOZ-objecten met postcode. [optional]
                huisnummer (int): Zoek WOZ-objecten met huisnummer\". [optional]
                fields (str): Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma's gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature). [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WozObjectHalCollectie
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.zoek_actuele_wozobjecten = Endpoint(
            settings={
                'response_type': (WozObjectHalCollectie,),
                'auth': [],
                'endpoint_path': '/wozobjecten',
                'operation_id': 'zoek_actuele_wozobjecten',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'rsin',
                    'kvk_nummer',
                    'adresseerbaar_object_identificatie',
                    'nummeraanduiding_identificatie',
                    'postcode',
                    'huisnummer',
                    'fields',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'postcode',
                    'huisnummer',
                ]
            },
            root_map={
                'validations': {
                    ('postcode',): {

                        'regex': {
                            'pattern': r'^[1-9][0-9][0-9][0-9][A-Z][A-Z]$',  # noqa: E501
                        },
                    },
                    ('huisnummer',): {

                        'inclusive_maximum': 99999,
                        'inclusive_minimum': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'rsin':
                        (str,),
                    'kvk_nummer':
                        (str,),
                    'adresseerbaar_object_identificatie':
                        (str,),
                    'nummeraanduiding_identificatie':
                        (str,),
                    'postcode':
                        (str,),
                    'huisnummer':
                        (int,),
                    'fields':
                        (str,),
                },
                'attribute_map': {
                    'rsin': 'rsin',
                    'kvk_nummer': 'kvkNummer',
                    'adresseerbaar_object_identificatie': 'adresseerbaarObjectIdentificatie',
                    'nummeraanduiding_identificatie': 'nummeraanduidingIdentificatie',
                    'postcode': 'postcode',
                    'huisnummer': 'huisnummer',
                    'fields': 'fields',
                },
                'location_map': {
                    'rsin': 'query',
                    'kvk_nummer': 'query',
                    'adresseerbaar_object_identificatie': 'query',
                    'nummeraanduiding_identificatie': 'query',
                    'postcode': 'query',
                    'huisnummer': 'query',
                    'fields': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/hal+json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__zoek_actuele_wozobjecten
        )
