/* 
 * Waardering onroerende zaken
 *
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WozObjectBasisLinks
    /// </summary>
    [DataContract]
    public partial class WozObjectBasisLinks :  IEquatable<WozObjectBasisLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WozObjectBasisLinks" /> class.
        /// </summary>
        /// <param name="self">self.</param>
        /// <param name="adres">adres.</param>
        /// <param name="adresseerbaarObjecten">adresseerbaarObjecten.</param>
        /// <param name="belanghebbendEigenaar">belanghebbendEigenaar.</param>
        /// <param name="belanghebbendGebruiker">belanghebbendGebruiker.</param>
        /// <param name="panden">panden.</param>
        public WozObjectBasisLinks(HalLink self = default(HalLink), HalLink adres = default(HalLink), List<HalLink> adresseerbaarObjecten = default(List<HalLink>), HalLink belanghebbendEigenaar = default(HalLink), HalLink belanghebbendGebruiker = default(HalLink), List<HalLink> panden = default(List<HalLink>))
        {
            this.Self = self;
            this.Adres = adres;
            this.AdresseerbaarObjecten = adresseerbaarObjecten;
            this.BelanghebbendEigenaar = belanghebbendEigenaar;
            this.BelanghebbendGebruiker = belanghebbendGebruiker;
            this.Panden = panden;
        }
        
        /// <summary>
        /// Gets or Sets Self
        /// </summary>
        [DataMember(Name="self", EmitDefaultValue=false)]
        public HalLink Self { get; set; }

        /// <summary>
        /// Gets or Sets Adres
        /// </summary>
        [DataMember(Name="adres", EmitDefaultValue=false)]
        public HalLink Adres { get; set; }

        /// <summary>
        /// Gets or Sets AdresseerbaarObjecten
        /// </summary>
        [DataMember(Name="adresseerbaarObjecten", EmitDefaultValue=false)]
        public List<HalLink> AdresseerbaarObjecten { get; set; }

        /// <summary>
        /// Gets or Sets BelanghebbendEigenaar
        /// </summary>
        [DataMember(Name="belanghebbendEigenaar", EmitDefaultValue=false)]
        public HalLink BelanghebbendEigenaar { get; set; }

        /// <summary>
        /// Gets or Sets BelanghebbendGebruiker
        /// </summary>
        [DataMember(Name="belanghebbendGebruiker", EmitDefaultValue=false)]
        public HalLink BelanghebbendGebruiker { get; set; }

        /// <summary>
        /// Gets or Sets Panden
        /// </summary>
        [DataMember(Name="panden", EmitDefaultValue=false)]
        public List<HalLink> Panden { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WozObjectBasisLinks {\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("  Adres: ").Append(Adres).Append("\n");
            sb.Append("  AdresseerbaarObjecten: ").Append(AdresseerbaarObjecten).Append("\n");
            sb.Append("  BelanghebbendEigenaar: ").Append(BelanghebbendEigenaar).Append("\n");
            sb.Append("  BelanghebbendGebruiker: ").Append(BelanghebbendGebruiker).Append("\n");
            sb.Append("  Panden: ").Append(Panden).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WozObjectBasisLinks);
        }

        /// <summary>
        /// Returns true if WozObjectBasisLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of WozObjectBasisLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WozObjectBasisLinks input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Self == input.Self ||
                    (this.Self != null &&
                    this.Self.Equals(input.Self))
                ) && 
                (
                    this.Adres == input.Adres ||
                    (this.Adres != null &&
                    this.Adres.Equals(input.Adres))
                ) && 
                (
                    this.AdresseerbaarObjecten == input.AdresseerbaarObjecten ||
                    this.AdresseerbaarObjecten != null &&
                    input.AdresseerbaarObjecten != null &&
                    this.AdresseerbaarObjecten.SequenceEqual(input.AdresseerbaarObjecten)
                ) && 
                (
                    this.BelanghebbendEigenaar == input.BelanghebbendEigenaar ||
                    (this.BelanghebbendEigenaar != null &&
                    this.BelanghebbendEigenaar.Equals(input.BelanghebbendEigenaar))
                ) && 
                (
                    this.BelanghebbendGebruiker == input.BelanghebbendGebruiker ||
                    (this.BelanghebbendGebruiker != null &&
                    this.BelanghebbendGebruiker.Equals(input.BelanghebbendGebruiker))
                ) && 
                (
                    this.Panden == input.Panden ||
                    this.Panden != null &&
                    input.Panden != null &&
                    this.Panden.SequenceEqual(input.Panden)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Self != null)
                    hashCode = hashCode * 59 + this.Self.GetHashCode();
                if (this.Adres != null)
                    hashCode = hashCode * 59 + this.Adres.GetHashCode();
                if (this.AdresseerbaarObjecten != null)
                    hashCode = hashCode * 59 + this.AdresseerbaarObjecten.GetHashCode();
                if (this.BelanghebbendEigenaar != null)
                    hashCode = hashCode * 59 + this.BelanghebbendEigenaar.GetHashCode();
                if (this.BelanghebbendGebruiker != null)
                    hashCode = hashCode * 59 + this.BelanghebbendGebruiker.GetHashCode();
                if (this.Panden != null)
                    hashCode = hashCode * 59 + this.Panden.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
