/*
 * Waardering onroerende zaken
 *
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WozObjectHalCollectieEmbedded
    /// </summary>
    [DataContract]
    public partial class WozObjectHalCollectieEmbedded :  IEquatable<WozObjectHalCollectieEmbedded>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WozObjectHalCollectieEmbedded" /> class.
        /// </summary>
        /// <param name="wozObjecten">wozObjecten.</param>
        public WozObjectHalCollectieEmbedded(List<WozObjectHal> wozObjecten = default(List<WozObjectHal>))
        {
            this.WozObjecten = wozObjecten;
        }

        /// <summary>
        /// Gets or Sets WozObjecten
        /// </summary>
        [DataMember(Name="wozObjecten", EmitDefaultValue=false)]
        public List<WozObjectHal> WozObjecten { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WozObjectHalCollectieEmbedded {\n");
            sb.Append("  WozObjecten: ").Append(WozObjecten).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WozObjectHalCollectieEmbedded);
        }

        /// <summary>
        /// Returns true if WozObjectHalCollectieEmbedded instances are equal
        /// </summary>
        /// <param name="input">Instance of WozObjectHalCollectieEmbedded to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WozObjectHalCollectieEmbedded input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WozObjecten == input.WozObjecten ||
                    this.WozObjecten != null &&
                    input.WozObjecten != null &&
                    this.WozObjecten.SequenceEqual(input.WozObjecten)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WozObjecten != null)
                    hashCode = hashCode * 59 + this.WozObjecten.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
