/* 
 * Waardering onroerende zaken
 *
 * Deze API levert actuele gegevens over WOZ-objecten 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWOZObjectenApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>WozObjectHal</returns>
        WozObjectHal RaadpleegActueelWozobject (string identificatie, string fields = default(string));

        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>ApiResponse of WozObjectHal</returns>
        ApiResponse<WozObjectHal> RaadpleegActueelWozobjectWithHttpInfo (string identificatie, string fields = default(string));
        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>WozObjectHalCollectie</returns>
        WozObjectHalCollectie ZoekActueleWozobjecten (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string));

        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>ApiResponse of WozObjectHalCollectie</returns>
        ApiResponse<WozObjectHalCollectie> ZoekActueleWozobjectenWithHttpInfo (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of WozObjectHal</returns>
        System.Threading.Tasks.Task<WozObjectHal> RaadpleegActueelWozobjectAsync (string identificatie, string fields = default(string), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Raadpleeg een WOZ-object
        /// </summary>
        /// <remarks>
        /// Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (WozObjectHal)</returns>
        System.Threading.Tasks.Task<ApiResponse<WozObjectHal>> RaadpleegActueelWozobjectWithHttpInfoAsync (string identificatie, string fields = default(string), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of WozObjectHalCollectie</returns>
        System.Threading.Tasks.Task<WozObjectHalCollectie> ZoekActueleWozobjectenAsync (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Zoek WOZ-objecten
        /// </summary>
        /// <remarks>
        /// Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (WozObjectHalCollectie)</returns>
        System.Threading.Tasks.Task<ApiResponse<WozObjectHalCollectie>> ZoekActueleWozobjectenWithHttpInfoAsync (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WOZObjectenApi : IWOZObjectenApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WOZObjectenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WOZObjectenApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WOZObjectenApi"/> class
        /// </summary>
        /// <returns></returns>
        public WOZObjectenApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WOZObjectenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WOZObjectenApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>WozObjectHal</returns>
        public WozObjectHal RaadpleegActueelWozobject (string identificatie, string fields = default(string))
        {
             ApiResponse<WozObjectHal> localVarResponse = RaadpleegActueelWozobjectWithHttpInfo(identificatie, fields);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>ApiResponse of WozObjectHal</returns>
        public ApiResponse<WozObjectHal> RaadpleegActueelWozobjectWithHttpInfo (string identificatie, string fields = default(string))
        {
            // verify the required parameter 'identificatie' is set
            if (identificatie == null)
                throw new ApiException(400, "Missing required parameter 'identificatie' when calling WOZObjectenApi->RaadpleegActueelWozobject");

            var localVarPath = "/wozobjecten/{identificatie}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (identificatie != null) localVarPathParams.Add("identificatie", this.Configuration.ApiClient.ParameterToString(identificatie)); // path parameter
            if (fields != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fields", fields)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RaadpleegActueelWozobject", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WozObjectHal>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WozObjectHal) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WozObjectHal)));
        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of WozObjectHal</returns>
        public async System.Threading.Tasks.Task<WozObjectHal> RaadpleegActueelWozobjectAsync (string identificatie, string fields = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<WozObjectHal> localVarResponse = await RaadpleegActueelWozobjectWithHttpInfoAsync(identificatie, fields, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Raadpleeg een WOZ-object Raadpleeg de actuele eigenschappen van een WOZ-object
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificatie">Unieke identificatie van een WOZ-object</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (WozObjectHal)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WozObjectHal>> RaadpleegActueelWozobjectWithHttpInfoAsync (string identificatie, string fields = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'identificatie' is set
            if (identificatie == null)
                throw new ApiException(400, "Missing required parameter 'identificatie' when calling WOZObjectenApi->RaadpleegActueelWozobject");

            var localVarPath = "/wozobjecten/{identificatie}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (identificatie != null) localVarPathParams.Add("identificatie", this.Configuration.ApiClient.ParameterToString(identificatie)); // path parameter
            if (fields != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fields", fields)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RaadpleegActueelWozobject", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WozObjectHal>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WozObjectHal) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WozObjectHal)));
        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>WozObjectHalCollectie</returns>
        public WozObjectHalCollectie ZoekActueleWozobjecten (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string))
        {
             ApiResponse<WozObjectHalCollectie> localVarResponse = ZoekActueleWozobjectenWithHttpInfo(rsin, kvkNummer, adresseerbaarObjectIdentificatie, nummeraanduidingIdentificatie, postcode, huisnummer, fields);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <returns>ApiResponse of WozObjectHalCollectie</returns>
        public ApiResponse<WozObjectHalCollectie> ZoekActueleWozobjectenWithHttpInfo (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string))
        {

            var localVarPath = "/wozobjecten";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rsin != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "rsin", rsin)); // query parameter
            if (kvkNummer != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "kvkNummer", kvkNummer)); // query parameter
            if (adresseerbaarObjectIdentificatie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "adresseerbaarObjectIdentificatie", adresseerbaarObjectIdentificatie)); // query parameter
            if (nummeraanduidingIdentificatie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "nummeraanduidingIdentificatie", nummeraanduidingIdentificatie)); // query parameter
            if (postcode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "postcode", postcode)); // query parameter
            if (huisnummer != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "huisnummer", huisnummer)); // query parameter
            if (fields != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fields", fields)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ZoekActueleWozobjecten", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WozObjectHalCollectie>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WozObjectHalCollectie) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WozObjectHalCollectie)));
        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of WozObjectHalCollectie</returns>
        public async System.Threading.Tasks.Task<WozObjectHalCollectie> ZoekActueleWozobjectenAsync (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<WozObjectHalCollectie> localVarResponse = await ZoekActueleWozobjectenWithHttpInfoAsync(rsin, kvkNummer, adresseerbaarObjectIdentificatie, nummeraanduidingIdentificatie, postcode, huisnummer, fields, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Zoek WOZ-objecten Zoek WOZ-objecten op eigenaar of adres. Het resultaat zijn de actuele gegevens van de gevonden objecten.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rsin">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven niet-natuurlijk persoon (optional)</param>
        /// <param name="kvkNummer">Zoek WOZ-objecten in eigendom van een bij het Handelsregister ingeschreven maatschappelijke activiteit of een van de daaronder vallende ondernemingen en vestigingen (optional)</param>
        /// <param name="adresseerbaarObjectIdentificatie">Zoek op de BAG identificatie van een adresseerbaar object (verblijfsobject, standplaats of ligplaats) waar het WOZ-object aan verbonden is of waar het object zijn aanduiding aan ontleent (optional)</param>
        /// <param name="nummeraanduidingIdentificatie">Zoek op de BAG identificatie van een nummeraanduiding (adres) waarmee het WOZ-object wordt aangeduid (optional)</param>
        /// <param name="postcode">Zoek WOZ-objecten met postcode (optional)</param>
        /// <param name="huisnummer">Zoek WOZ-objecten met huisnummer\&quot; (optional)</param>
        /// <param name="fields">Hiermee kun je de inhoud van de resource naar behoefte aanpassen door een door komma&#39;s gescheiden lijst van property namen op te geven. Bij opgave van niet-bestaande properties wordt een 400 Bad Request teruggegeven. Wanneer de fields parameter niet is opgegeven, worden alle properties met een waarde teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (WozObjectHalCollectie)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WozObjectHalCollectie>> ZoekActueleWozobjectenWithHttpInfoAsync (string rsin = default(string), string kvkNummer = default(string), string adresseerbaarObjectIdentificatie = default(string), string nummeraanduidingIdentificatie = default(string), string postcode = default(string), int? huisnummer = default(int?), string fields = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/wozobjecten";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rsin != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "rsin", rsin)); // query parameter
            if (kvkNummer != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "kvkNummer", kvkNummer)); // query parameter
            if (adresseerbaarObjectIdentificatie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "adresseerbaarObjectIdentificatie", adresseerbaarObjectIdentificatie)); // query parameter
            if (nummeraanduidingIdentificatie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "nummeraanduidingIdentificatie", nummeraanduidingIdentificatie)); // query parameter
            if (postcode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "postcode", postcode)); // query parameter
            if (huisnummer != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "huisnummer", huisnummer)); // query parameter
            if (fields != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fields", fields)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ZoekActueleWozobjecten", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WozObjectHalCollectie>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WozObjectHalCollectie) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WozObjectHalCollectie)));
        }

    }
}
